[package]
name = "crate1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macro_crate = { path = "../macro_crate" }
crate2 = { path = "../crate2" }

[features]
rosapi = []